### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by sophiahuxh** [sophiahuxh/wmb#1]
## TODOs
- [x] sc: store code to github repo
- [ ] server: install docker on linux
- [ ] server: prepare mongo and node env on linx - docker compose, mongo data stored in local, node container read code from local dir
- [x] db: create mongo account
- [x] db: move mongo database content to mongo server on linux box
- [x] code: update code to read mongo credential and location from environment variables
- [ ] server: pull code from repo to linux box (the dir node container will pull code from) 
- [ ] code: update readme to describe how to develop, how to deploy
